from .accessible_msg_dialog import AccessibleMsgDialog as AccessibleMsgDialog
from .visual_settings_dialog import VisualSettingsDialog as VisualSettingsDialog
from .player_enrollment_dialog import PlayerEnrollmentDialog as PlayerEnrollmentDialog
from .result_dialog import ResultDialog as ResultDialog
from .fide_query_dialog import FideQueryDialog as FideQueryDialog
from .sync_database_dialog import SyncDatabaseDialog as SyncDatabaseDialog
from .players_db_dialog import PlayersDbDialog as PlayersDbDialog
from .donation_dialog import DonationDialog as DonationDialog
from .tiebreak_config_dialog import TiebreakConfigDialog as TiebreakConfigDialog

