from .accessible_msg_dialog import AccessibleMsgDialog as AccessibleMsgDialog
from .visual_settings_dialog import VisualSettingsDialog as VisualSettingsDialog
from .player_enrollment_dialog import PlayerEnrollmentDialog as PlayerEnrollmentDialog
from .result_dialog import ResultDialog as ResultDialog
